FROM archlinux:base

RUN pacman --noconfirm -Syu \
	&& pacman --needed --noconfirm -S \
		base-devel \
		arp-scan \
		python \
		parted \
		dosfstools \
		rsync \
		linux-firmware-qlogic \
		devtools \
	&& (pacman --noconfirm -Sc || true)

RUN mkdir /tools
COPY install-binfmt /tools/
COPY docker-extract /tools/
